### ISSUE TITLE
depts.get()

### ISSUE THREAD

**Issue by io-ma** [alecraso/grnhse-api#2]
Hi, 
Thank you for sharing this little package.
Playing with in in Django shell.
I am trying to get the whole departments soup and I get a 401:
I follow your example, then do: depts.get()
HTTPError: 401 {"message":"Invalid Basic Auth credentials"}
How can I get the whole departments list?

![Desktop-screenshot (44)](https://user-images.githubusercontent.com/2306628/90643087-d86a1480-e23b-11ea-9c3e-0a3dc36ccb34.png)

**Comment by alecraso** [comment]
Been a while since I visited this code. I wonder if they've changed their authorization on the backend. Let me take a look today.

**Comment by alecraso** [comment]
I'm actually not able to replicate this. Running what you have above works for me. Perhaps your issue is improper permissions on your API key itself, or a typo in the key?

**Comment by io-ma** [comment]
hmmm... are you adding a : at the end of the key?
my key is of format:  '##################-#', but on their site they specify you should add a :
... tried adding a : at the end, no luck.
I can get the endpoints just fine using this script and my key:
```python
str = "########################-#:"
str_bytes = str.encode('ascii')
base_64_bytes = base64.b64encode(str_bytes)
base_64_message = base_64_bytes.decode('ascii')
headers = {"Authorization": "Basic " + base_64_message}
url = 'https://harvest.greenhouse.io/v1/candidates/'
response = requests.get(url, headers=headers)
response.text
```

**Comment by alecraso** [comment]
Hm that's strange it works one way but not another. The wrapper sets the authorization using `requests`. You shouldn't add a `:` to your key.
https://github.com/aaronbiller/grnhse-api/blob/24d22e34ee6a0c3d5e69b9f2dda0f6821501da53/grnhse/harvest/api.py#L25

Perhaps the wrapper should explicitly use basic auth for the api calls.

**Comment by io-ma** [comment]
Yes, but what puzzles me is it works on your end with just the key and the exact code :-D

**Comment by jpulec** [comment]
This bug is because `auth = (self._api_key, None)` gets encoded by requests as `<API_KEY>:None` since requests stringifies the `None` password to the string `None`. It seems that Greenhouse just happens to permit this with some API keys and not others. :man_shrugging: 

From what I can tell, it seems that older generated keys are fine with this, but more recent keys do not auth correctly with the `None` string appended. Fixing this should be as simple as passing the empty string to the auth object.

**Comment by io-ma** [comment]
This is genius @jpulec , thank you very much! @aaronbiller will this be included in the next release, or I better modify the file myself? Anyway, thank you again for sharing this one!
